// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0TPGNOuoVLB9OQ4JhAFmJHO8VH_ZTnpQ',
    appId: '1:79543153509:web:1e6488367b29022047a78c',
    messagingSenderId: '79543153509',
    projectId: 'fit2eat',
    authDomain: 'fit2eat.firebaseapp.com',
    storageBucket: 'fit2eat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTsjFhuaoLmSzU7tjF3aGC8pLkDkzBPAQ',
    appId: '1:79543153509:android:87ba0c3145ddf89a47a78c',
    messagingSenderId: '79543153509',
    projectId: 'fit2eat',
    storageBucket: 'fit2eat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASPgCFFIBQkt2O7cp1i4XdcSUEetVLxnM',
    appId: '1:79543153509:ios:8e8dd1ae741a253d47a78c',
    messagingSenderId: '79543153509',
    projectId: 'fit2eat',
    storageBucket: 'fit2eat.firebasestorage.app',
    iosBundleId: 'com.example.fit2eat',
  );
}
